### ISSUE TITLE
represent all snippets as either MD or HTML

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-ontology#4]
@hurngchunlee

 Most raw snippets are html but this one is md

https://github.com/donders-research-data-management/rdm-ontology/blob/master/privacy/privacy_policy.md

**Comment by hurngchunlee** [comment]
This file is not the snippet.  But it will be converted to HTML snippet using this script

https://github.com/donders-research-data-management/rdm-ontology/blob/master/tools/md2html.py

at the time of deployment to production.  Fixing it to HTML is possible, but it reduces the easiness of editing the file.

**Comment by robertoostenveld** [comment]
I am not opting for html over md, only for consistency. Why not have the same md2html conversion for all snippets?

**Comment by hurngchunlee** [comment]
Good question!  I don't see the need to enforce the consistency here, as long as the filename suffix reflects honestly to the format. 

Looking into the current HTML snippets, I see a file has difficulty to make it as Markdown format because the styling aspect is coded in to the HTML content.  The file is:

https://github.com/donders-research-data-management/rdm-ontology/blob/master/homepage/homepage.html

**Comment by robertoostenveld** [comment]
ok, let's close. 

The reason for me detecting this was because I explained Inge that - besides the context sensitive help to which the CMS points - we also have some text snippets in the CMS. I will bring this up on Friday in the D&I task group, as Inge, Katrin and Xiaochen should also know that they can (in principle) change those texts as well. Or suggest additional text snippets in the RDM CMS at locations that don't have such a snippet yet.
